# config.yaml

# 在GO中，所有属性绑定到结构体，都是小写

# HTTP模块设置
http:
  host: localhost                               # 监听地址
  port: 9044                                    # 监听端口

# 上传模块的相关设置

upload:
  path: uploads                                 # 文件上传的根目录
  # 普通文件上传
  file:
    path: files                                 # 文件上传的目录
    maxsize: 10485760                           # 上传文件的最大大小
    allowtype:                                  # 允许上传的文件后缀名
      - .log
      - .txt
      - .text
      - .md
  # 图片上传
  image:
    path: image                                 # 图片上传的目录
    maxsize: 10485760                           # 上传图片的最大大小
    thumbnail:
      path: thumbnail                           # 缩略图存放的目录
      maxwidth: 300                             # 缩略图最大宽度
      maxheight: 300                            # 缩略图最大高度
